name: "Setup Rust"
description: "Setup Rust"

outputs:
  rustc-hash:
    description: "Hash of the rustc version"
    value: ${{ steps.rust-version.outputs.rustc_hash }}

runs:
  using: "composite"
  steps:
    - name: Install system packages
      run: sudo apt-get update && sudo apt-get install -y build-essential libudev-dev
      shell: bash

    - name: Install Rust nightly
      run: |
        rustup default nightly
        rustup component add rustfmt clippy
      shell: bash

    - name: Install Cargo Expand
      run: cargo install --locked cargo-expand
      shell: bash

    - name: Get rustc version
      id: rust-version
      run: echo "rustc_hash=$(rustc -V | cut -d ' ' -f 3)" >> $GITHUB_ENV
      shell: bash
