name: Test Fuzz Tests

on:
  workflow_dispatch:
  pull_request:

env:
  SOLANA_CLI_VERSION: 1.18.18
  HONGGFUZZ_VERSION: 0.5.56
  TRIDENT_COMMIT_HASH: eb8f647104209323b53e3637d3d3c5b7d140d368  # Set desired commit hash here

jobs:
  simple-cpi-6:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Set Anchor Version
        run: echo "ANCHOR_VERSION=0.30.1" >> $GITHUB_ENV

      - uses: Swatinem/rust-cache@v2
        name: Cache Rust and its Packages

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust/

      - name: Setup Solana Environment
        uses: ./.github/actions/setup-solana/

      - name: Setup Trident with Specified Commit
        uses: ./.github/actions/setup-trident/
        with:
          commit-hash: ${{ env.TRIDENT_COMMIT_HASH }}

      - name: Setup Honggfuzz
        uses: ./.github/actions/setup-honggfuzz/
        id: rust-setup

      - name: Run Fuzz Tests
        run: trident fuzz run fuzz_0
